//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace plakplak.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokemons
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int TypeId { get; set; }
        public int AbilityId { get; set; }
    
        public virtual Abilities Abilities { get; set; }
        public virtual Types Types { get; set; }
    }
}
